// Generated by https://quicktype.io

class PopularModel {
  bool? adult;
  String? backdropPath;
  int? budget;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  int? runtime;
  String? title;
  double? voteAverage;
  int? voteCount;

  PopularModel({
    this.adult,
    this.backdropPath,
    this.budget,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.runtime,
    this.title,
    this.voteAverage,
    this.voteCount,
  });
  factory PopularModel.fromMap(Map<String, dynamic> movie) {
    return PopularModel(
      id: movie['id'],
      adult: movie['adult'],
      backdropPath: movie['backdrop_path'],
      budget: movie['budget'],
      posterPath: movie['poster_path'],
      originalLanguage: movie['original_language'],
      originalTitle: movie['original_title'],
      overview: movie['overview'],
      popularity: movie['popularity'],
      releaseDate: movie['release_date'],
      runtime: movie['runtime'],
      title: movie['title'],
      voteAverage: movie['vote_average'],
      voteCount: movie['vote_count'], // Generated by https://quicktype.io
    );
  }
  factory PopularModel.fromJson(Map<String, dynamic> json) {
    return PopularModel(
      id: json['id'],
      adult: json['adult'],
      backdropPath: json['backdrop_path'],
      budget: json['budget'],
      posterPath: json['poster_path'],
      originalLanguage: json['original_language'],
      originalTitle: json['original_title'],
      overview: json['overview'],
      popularity: json['popularity'],
      releaseDate: json['release_date'],
      runtime: json['runtime'],
      title: json['title'],
      voteAverage: json['vote_average'],
      voteCount: json['vote_count'],
    );
  }
}
